DROP TABLE IF EXISTS bookings;
DROP TABLE IF EXISTS showtimes;
DROP TABLE IF EXISTS movies;

-- Movies table
CREATE TABLE movies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255),
    genre VARCHAR(255),
    duration INTEGER NOT NULL,
    rating VARCHAR(255) NOT NULL,
    release_year INTEGER NOT NULL
);

-- Showtimes table
CREATE TABLE showtimes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    movie_id BIGINT,
    theater VARCHAR(255),
    start_time TIMESTAMP,
    end_time TIMESTAMP,
    price DOUBLE PRECISION NOT NULL,
    FOREIGN KEY (movie_id) REFERENCES movies(id)
);

-- Bookings table
CREATE TABLE bookings (
    booking_id UUID PRIMARY KEY,
    showtime_id BIGINT,
    seat_number INTEGER NOT NULL,
    user_id UUID,
    FOREIGN KEY (showtime_id) REFERENCES showtimes(id),
    CONSTRAINT unique_showtime_seat UNIQUE (showtime_id, seat_number)
);